"""
Django settings for champions project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.conf import settings
from django.conf.urls.static import static
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ean#ub7o)9we4i+ep1!dz3t*luxeqnua^j!x#b6y4=lgsi1#u('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'champion',
     'crispy_forms',
    'crispy_bootstrap4',
    'paypal.standard.ipn',
    'Team_dashboard',
    'channels',
    'ckeditor',
    'storages',
    'nexus',
]
X_FRAME_OPTIONS = 'SAMEORIGIN'
CRISPY_TEMPLATE_PACK = 'bootstrap4'  # or 'bootstrap5' or any other pack you use
PAYPAL_RECEIVER_EMAIL = 'sb-dnlrv32270792@business.example.com'

PAYPAL_TEST = True
RAZORPAY_KEY_ID = 'rzp_test_wdTOpH9mNp17DE'
RAZORPAY_KEY_SECRET = 'bAXbGVKOTPUghSx6ZokPZwZT'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'champion.middleware.PendingApprovalMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'champions.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'nexus.notifications.notifications_count_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'champions.wsgi.application'

import os

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'champion_db',
        'USER': 'root',  # Default XAMPP MySQL user
        'PASSWORD': '',  # Leave empty if there's no password
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
        },
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'champions_db',
#         'USER': 'codex',  # Default XAMPP MySQL user
#         'PASSWORD': 'Hacker@9829593419',  # Leave empty if there's no password
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }
# settings.py
BREVO_SMTP_USERNAME = 'kpkbon@gmail.com'
BREVO_SMTP_PASSWORD = 'xsmtpsib-93e2dba31e0798288d4e0114bdd1f10ddb85ef59a7b4d91f77747e5799a069ff-PXvw6ycDsO4jQaZF'

# Default email settings
DEFAULT_FROM_EMAIL = 'Service@thechampionsclub.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = BREVO_SMTP_USERNAME
EMAIL_HOST_PASSWORD = BREVO_SMTP_PASSWORD


# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

 # Store results in the database
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
ASGI_APPLICATION = 'champions.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}
LOGIN_URL = '/login/'
# STATIC_URL = '/static/'

# In development, STATICFILES_DIRS should point to the location of your static files
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# # In production, STATIC_ROOT is used to collect static files into a single directory
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # This is only used in production
AWS_ACCESS_KEY_ID = 'AKIAR56Q2FALOZSAAMPZ'
AWS_SECRET_ACCESS_KEY = 'KzGyOrBAtMSs8dqnPpgMVU02zMTQeWQGBdg5+CAj'
AWS_STORAGE_BUCKET_NAME = 'thechampionsclubmedia'
AWS_S3_REGION_NAME = 'ap-south-1'  # Replace with your bucket's region
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.ap-south-1.amazonaws.com'

# Caching and Static Settings
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

# Static files settings
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Media files settings
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'