# Generated by Django 5.0.7 on 2024-09-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("champion", "0007_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="date",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(),
        ),
    ]
