# Generated by Django 5.0.7 on 2024-09-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("champion", "0009_donation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("company_name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                ("phone", models.CharField(max_length=15)),
                ("message", models.TextField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
