# Generated by Django 5.0.7 on 2024-09-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("champion", "0010_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionalDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
