# Generated by Django 5.0.7 on 2024-09-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("champion", "0012_jobcategory_jobpost_jobapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video", models.FileField(upload_to="reels/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="reels/thumbnails/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
