# Generated by Django 5.0.7 on 2024-09-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("champion", "0013_reel"),
    ]

    operations = [
        migrations.AddField(
            model_name="reel",
            name="compressed_video",
            field=models.FileField(
                blank=True, null=True, upload_to="reels/compressed/"
            ),
        ),
        migrations.AddField(
            model_name="reel",
            name="compression_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reel",
            name="is_compressed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reel",
            name="video",
            field=models.FileField(upload_to="reels/originals/"),
        ),
    ]
