# Generated by Django 5.0.7 on 2024-10-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion', '0015_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
