# Generated by Django 5.0.7 on 2024-10-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion', '0017_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview_file',
            field=models.FileField(upload_to='podcasts/previews/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='podcasts/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='podcasts/'),
        ),
    ]
