# Generated by Django 5.0.7 on 2024-10-09 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion', '0019_supportrequest_email_supportrequest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lesson',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='champion.video'),
        ),
    ]
