# Generated by Django 5.0.7 on 2024-10-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion', '0023_remove_reel_reel_category_reel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='show_visit_now_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reel',
            name='visit_now_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
