# Generated by Django 5.0.7 on 2024-10-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion', '0024_reel_show_visit_now_button_reel_visit_now_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
