# Generated by Django 5.0.7 on 2024-11-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0002_remove_follow_registration_follow_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
