# Generated by Django 5.0.7 on 2024-11-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0008_remove_activitylog_action_activitylog_actor_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='activitylog',
        #     name='event_type',
        # ),
        # migrations.RemoveField(
        #     model_name='activitylog',
        #     name='related_tweet',
        # ),
        # migrations.AddField(
        #     model_name='activitylog',
        #     name='action',
        #     field=models.CharField(blank=True, choices=[('like', 'Like'), ('retweet', 'Retweet'), ('follow', 'Follow'), ('post', 'Post')], max_length=50),
        # ),
        # migrations.AlterField(
        #     model_name='activitylog',
        #     name='actor',
        #     field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_actor', to='nexus.userprofile'),
        # ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
