# Generated by Django 5.0.7 on 2024-11-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0009_remove_activitylog_event_type_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='activitylog',
        #     name='event_type',
        # ),
        # migrations.RemoveField(
        #     model_name='activitylog',
        #     name='related_tweet',
        # ),
        # migrations.AddField(
        #     model_name='activitylog',
        #     name='action',
        #     field=models.CharField(blank=True, choices=[('like', 'Like'), ('retweet', 'Retweet'), ('follow', 'Follow'), ('post', 'Post')], max_length=50),
        # ),
    ]
