# Generated by Django 5.0.7 on 2025-02-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0014_remove_notification_origin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='forwards_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
